### PR TITLE
Adding an PackSize for the 2200 mAh cylindrical battery: https://www.adafruit.com/product/1781

### PR DESCRIPTION
**Pull request by edanidzerda**
I'm using the 2200 mAh battery in my project with an ESP32-S2.  While it is working perfectly using a value of PackSize.MAH2000, I wanted to be able to specify the _perfect_ PackSize.  I tested this one line patch on my ESP32-S2.  I  couldn't tell a difference in the output, although I only tested the "cell percent" from between 90.4 and 94.9.

Thanks for everyone's work on CircuitPython!  It's really been a pleasure to work with.

### CODE REVIEW

**Comment by edanidzerda** [comment]
For the record, I did totally guess at the "value" of 0x2F.  2000 used 0x2D, so I left a space for 2100 if that used 0x2E...  I found the datasheet https://cdn-shop.adafruit.com/product-files/1781/C2253_-_ICR18650_2200mAh_3.7V_with_PCM_20140728_APPROVED_8.18.pdf but I couldn't find anything that looked like the values in PackSize structure.  😞

**Comment by jposada202020** [comment]
Just for reference, of the reviewer values comes from this graph.
image
And then convert to HEX

**Comment by dhalbert** [comment]
@jposada202020 so do you think the value chosen (0x2f == 47) is the best choice?

**Comment by jposada202020** [comment]
@dhalbert I would prefer that we use  (0x2f == 48)
image

**Comment by dhalbert** [comment]
@edanidzerda Based on the graph measurements above, how about 0x30 (= 48 decimal)?

**Comment by edanidzerda** [comment]
I did more pixel peeping on the image that I would like to admit 😄 Based on the purple line being 3 pixels high, I agree: there is only room for one more 3 pixel line to fit "49" under the line on the chart for 50.

I pushed a commit updating to 0x30, let me know if there's anything else I can do to help.

**Review by jposada202020 — APPROVED** [review]
Thank you very much @edanidzerda!. :) LGTM. At least in the future if folks find a problem they cannot say that we did not take a `closer` look 🔎

**Pull request merged**
